### ISSUE TITLE
RabbitMQ missing on b1, c1 and d1 

### ISSUE THREAD

**Issue by dpatel7** [filetrust/program-icap#189] opened 2021-01-26 14:29 UTC
Rancher Clusters b1, c1 and d1 all have no rabbitmq servers. Same issue as we saw yesterday. These must be not having rabbitmq deployed on these specific servers.
My theory is this is why were are getting 403 errors in current tests as loadbalancers are sending traffic to these servers with no queue so the file will never be processed

The Load Balancer is still sending traffic to these endpoints and we are seeing 403s.
![image](https://user-images.githubusercontent.com/61416876/105857952-b6db3900-5fe2-11eb-86f3-dff27ba79a9b.png)
![image](https://user-images.githubusercontent.com/61416876/105858264-04f03c80-5fe3-11eb-9b02-86534cc5d321.png)
![image](https://user-images.githubusercontent.com/61416876/105858391-2d783680-5fe3-11eb-96cf-1ad544fd8426.png)

**Comment by dpatel7** [comment] 2021-01-26 14:47
Reduced worker nodes for b1, c1 and d1 to 0, so loadbalancer would no longer send traffic here and errors ceased, satisfying the above conclusion 
![screencapture-34-242-5-130-3000-d-dujr-efMz-rancherlb-icap-live-performance-dashboard-2021-01-26-14_45_20](https://user-images.githubusercontent.com/61416876/105860424-75985880-5fe5-11eb-9601-137102bb81fb.png)

**Comment by Kirsten-Osborn** [comment] 2021-01-26 15:47
@dpatel7 @jpoolGW we are redeploying the clusters.  FYI the team have advised that reducing the worker nodes to 0 is likely to break the clusters, and alternative ways should be used to manage traffic.

**Comment by dpatel7** [comment] 2021-01-27 10:17
@tasssko @gargath We have seen still above issue on new deployment yesterday. 
![image](https://user-images.githubusercontent.com/61416876/105977033-d167ed80-6088-11eb-812c-7b96eb5080f9.png)

**Comment by Kirsten-Osborn** [comment] 2021-01-27 10:46
@dpatel7 @jpoolGW the team's preferred approach would be for you to document the problem and hand over to us i.e. not trying to “exclude” it.  Tass and Khoovi are on a call now to debug based on your latest update.  For future reference though, you can remove the unhealthy nodes from the regional load balancer through the Azure console, as long as you leave 1 on the worker scaleset and not 0.

**Comment by jpoolGW** [comment] 2021-01-27 11:17
@Kirsten-Osborn To clarify, the new clusters that were redeployed yesterday by @khoovirajsingh still show the same issues.
We have not made any changes to the clusters, or sent any traffic through them.
The clusters are as new, and are missing these services, on the same clusters, as at least the last 3 times this has been redeployed.
This would indicate to me that the issue is somewhere in the deployment script. That is where I would be focusing attention for any fixes.
We will leave these clusters untouched while this is being rectified.

**Comment by MattCavey** [comment] 2021-02-12 14:48
Closing

**Closed by MattCavey** 2021-02-12 14:49 UTC
Labels: P1, Rancher-Azure, bug
