### ISSUE TITLE
Rancher Clusters can become unstable after scaling to between 20-30 nodes

### ISSUE THREAD

**Issue by jpoolGW** [filetrust/program-icap#168] opened 2021-01-06 16:22 UTC
**Repro Steps** 

- In Azure Portal incrementally scale the clusters worker nodes by intervals of up to 5 nodes per scale
- Wait for nodes to display with a healthy state before adding a new batch of up to 5

**Outcome:** This can result in the cluster becoming unstable, what this looks like is nodes that have already been created and are in a stable state suddenly start to become unhealthy, these will then continuously swap between unhealthy and healthy.
Removing some unhealthy nodes does seem to eventually restore stability, however I have found when this happens that the following services enter a crashloop state due to being unable to connect to rabbitmq service

- Adaptation Service
- Archive-Adaptation Service
-  Event-Submission Service

This has now occurred on both clusters which probably need a redeployment as no files can be processed
![image](https://user-images.githubusercontent.com/60877176/103792229-4a9c9380-503b-11eb-9028-3e9493236478.png)

**Comment by jpoolGW** [comment] 2021-01-06 16:23
I suggest for the current configuration we should not exceed more than 20 worker nodes

**Comment by MattCavey** [comment] 2021-01-06 16:30
`Error while waiting for Mnesia tables: {timeout_waiting_for_tables,['rabbit@rabbitmq-service-server-2.rabbitmq-service-nodes.icap-adaptation','rabbit@rabbitmq-service-server-1.rabbitmq-service-nodes.icap-adaptation','rabbit@rabbitmq-service-server-0.rabbitmq-service-nodes.icap-adaptation'],[rabbit_durable_queue]}
2021-01-05 15:43:09.292 [info] <0.273.0> Waiting for Mnesia tables for 30000 ms, 8 retries left
2021-01-05 15:43:39.293 [warning] <0.273.0> Error while waiting for Mnesia tables: {timeout_waiting_for_tables,['rabbit@rabbitmq-service-server-2.rabbitmq-service-nodes.icap-adaptation','rabbit@rabbitmq-service-server-1.rabbitmq-service-nodes.icap-adaptation','rabbit@rabbitmq-service-server-0.rabbitmq-service-nodes.icap-adaptation'],[rabbit_durable_queue]}
2021-01-05 15:43:39.293 [info] <0.273.0> Waiting for Mnesia tables for 30000 ms, 7 retries left`

**Comment by tasssko** [comment] 2021-01-07 17:42
This is something that I will look at next week, my time is occupied with other work at the moment.

**Comment by NadHodeGW** [comment] 2021-01-07 17:51
Update from Jamie: The health state issues were caused by kubernetes service using same port as azure health checks, causing intermittent failure of health checks, 
kube services going into crashloop state not reproduced today.
I'm setting this to Review/QA for further testing tomorrow

**Comment by dpatel7** [comment] 2021-01-08 11:53
@tasssko Have seen same issue while try to scale the node on gw-icap-prd-ukw-c1-worker .

currently i have started with incremental of 5.

Couple of nodes are switching Health and Unhealthy without any load.
![image](https://user-images.githubusercontent.com/61416876/104012640-12ff2a00-51a8-11eb-9923-7f9bc3bde647.png)
![image](https://user-images.githubusercontent.com/61416876/104012655-1abece80-51a8-11eb-9dfd-6d0fb93af6a3.png)

**Comment by dpatel7** [comment] 2021-01-08 16:17
From Tass Skoudros (Servana)  
Dharam Patel you shouldn’t change any port
if a node is unhealthy its because it hasn’t provisioned kubernetes so the service is not live, hence nothing is listening on that port (edited) 

I have move the ticket back to In progress

**Comment by dpatel7** [comment] 2021-01-14 09:05
We successfully Manage to get 50 nodes and only 1 node fail to be unhealthy. I am moving this ticket to under review

**Comment by dpatel7** [comment] 2021-02-05 16:19
Haven't seen this issue any more

**Closed by dpatel7** 2021-02-05 16:19 UTC
Labels: P2, bug, under review
